### ISSUE TITLE
Tidy data

### ISSUE THREAD

**Issue by timotejvesel** [brinaribic/APPR-2020-21#1]
Opazil sem, da nekatere tabele še niso v obliki tidy data (npr. `place`, `place_Evropa`). V vsaki vrstici moraš imeti le eno meritev (t.j. vrednost za le eno leto).
V tabeli `regije` pa vrstic, kjer je vrednost v stolpcu `REGIJE` enaka `SLOVENIJA` ,ne potrebuješ, saj lahko te vrednosti dobiš kot vsoto vrednosti v vseh regija.

**Comment by brinaribic** [comment]
Hvala, sem uredila.

**Comment by timotejvesel** [comment]
V tidy data še nista tabeli `bdp_regije` ter `bdp_skupaj`.
